const properties = [
  {
    id: 1,
    building: "23",
    street: "Sandhills",
    region: "Wallington",
    town: "London",
    postcode: "SM6 8JE",
    tenantName: "Johnathan",
    tenantPhoneNumber: "0732124632",
    tenantEmailAddress: "johnathan@email.com",
  },
  {
    id: 2,
    building: "46",
    street: "Green Lane",
    region: "Croydon",
    town: "London",
    postcode: "CR0 2JN",
    tenantName: "Sarah",
    tenantPhoneNumber: "0745123461",
    tenantEmailAddress: "sarah@email.com",
  },
  {
    id: 3,
    building: "57",
    street: "Maple Street",
    region: "Bromley",
    town: "London",
    postcode: "BR1 1BA",
    tenantName: "Michael",
    tenantPhoneNumber: "0764123456",
    tenantEmailAddress: "michael@email.com",
  },
  {
    id: 4,
    building: "82",
    street: "Park Avenue",
    region: "Sutton",
    town: "London",
    postcode: "SM1 2JT",
    tenantName: "Emily",
    tenantPhoneNumber: "0785123654",
    tenantEmailAddress: "emily@email.com",
  },
  {
    id: 5,
    building: "21",
    street: "Victoria Road",
    region: "Merton",
    town: "London",
    postcode: "ME1 2NE",
    tenantName: "David",
    tenantPhoneNumber: "0705123897",
    tenantEmailAddress: "david@email.com",
  },
  {
    id: 6,
    building: "34",
    street: "High Street",
    region: "Richmond",
    town: "London",
    postcode: "RH1 3DE",
    tenantName: "Samantha",
    tenantPhoneNumber: "0735123098",
    tenantEmailAddress: "samantha@email.com",
  },
  {
    id: 7,
    building: "19",
    street: "Church Road",
    region: "Kingston",
    town: "London",
    postcode: "KG1 4FG",
    tenantName: "Robert",
    tenantPhoneNumber: "0765123045",
    tenantEmailAddress: "robert@email.com",
  },
  {
    id: 8,
    building: "29",
    street: "Park Road",
    region: "Hammersmith",
    town: "London",
    postcode: "HM2 3WE",
    tenantName: "Jessica",
    tenantPhoneNumber: "0725123789",
    tenantEmailAddress: "jessica@email.com",
  },
  {
    id: 9,
    building: "45",
    street: "Queens Road",
    region: "Fulham",
    town: "London",
    postcode: "FL3 6TY",
    tenantName: "James",
    tenantPhoneNumber: "0795123876",
    tenantEmailAddress: "james@email.com",
  },
];

export default properties;
